use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    cxx_build::bridge("src/lib.rs")
        .include("include")
        .std("c++20")
        .compile("calculator");

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=include/calc_def.h");

    // Export the autogenerated C++ header to include/calculator.h and inject C++20 `using enum`
    // declarations so enumerators can be accessed without the `EnumName::` prefix.
    if let Ok(out_dir) = env::var("OUT_DIR") {
        let generated_header = PathBuf::from(&out_dir)
            .join("cxxbridge")
            .join("include")
            .join("rust-toy")
            .join("src")
            .join("lib.rs.h");
        if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
            let include_dir = PathBuf::from(manifest_dir).join("include");
            let _ = fs::create_dir_all(&include_dir);
            if let Ok(header_content) = fs::read_to_string(&generated_header) {
                let mut processed = String::with_capacity(header_content.len() + 128);
                for line in header_content.lines() {
                    if let Some(enum_name) = line.strip_prefix("#endif // CXXBRIDGE1_ENUM_") {
                        processed.push_str(&format!("using enum {};\n", enum_name.trim()));
                    }
                    processed.push_str(line);
                    processed.push('\n');
                }
                let _ = fs::write(include_dir.join("calculator.h"), processed);
            }
        }
    }
}
